#!/usr/bin/env bash
# Copyright (c) 2023 rM-self-serve
# SPDX-License-Identifier: MIT

webinterface_onboot_version='v1.2.0'

main() {
	# collect options before or after command
	no_prompt=false
	if nop_match "$1"; then
		no_prompt=true
		shift
	fi
	cmd=("$1")
	if [[ "$2" != "" ]]; then
		shift
		if [ "$no_prompt" == false ] && nop_match "$1"; then
			no_prompt=true
			shift
		fi
		cmd+=("$@")
	fi

	case ${cmd[@]} in
	'-h' | '--help' | '')
		cli_info
		;;
	'-s' | '--status')
		status
		;;
	'local-exec')
		run
		;;
	'apply-hack')
		checkspace
		apply_hack
		;;
	'revert-hack')
		checkspace
		revert_hack
		;;
	'apply-prstip')
		checkspace
		apply_prstip
		;;
	'revert-prstip')
		checkspace
		revert_prstip
		;;
	*)
		echo 'input not recognized'
		cli_info
		;;
	esac
}

checkspace() {
	if ! _checkspace / 1; then
		(
			echo "Not enough space on /"
			echo "Try to free space by running: journalctl --vacuum-time=1m"
			echo "Or: systemctl restart xochitl"
			exit 10
		)
		exit 1
	fi
	if ! _checkspace /home 10; then
		(
			echo "Not enough space on /home"
			exit 10
		)
		exit 1
	fi
}

_checkspace() {
	part=$1
	needed=$2
	_available=$(df "$part" | tail -n1 | awk '{print $4}')
	available=$(("$_available" / 1024))
	if [ $available -lt "$needed" ]; then
		echo "Less than ${needed}MB free, ${available}MB"
		return 1
	fi
}

nop_match() {
	[[ "$1" == *"-y"* ]] || [[ "$1" == *"--no-prompt"* ]]
}

cli_info() {
	echo -e "${GREEN}webinterface-onboot ${webinterface_onboot_version}${NC}"
	echo ''
	echo 'This simple program will convince the ReMarkable Tablet to start'
	echo 'the web interface after booting without the usb cord being plugged in.'
	echo 'Xochitl versions >= v2.15 require simple binary hack.'
	echo 'Use the persist ip modification to keep the web interface accessible'
	echo 'after unplugging the cable.'
	echo 'Source+Docs: https://github.com/rM-self-serve/webinterface-onboot'
	echo ''
	echo -e "${CYAN}ENABLE/USE:${NC}"
	echo '$ systemctl enable --now webinterface-onboot'
	echo ''
	echo -e "${CYAN}DISABLE:${NC}"
	echo '$ systemctl disable --now webinterface-onboot'
	echo ''
	echo -e "${CYAN}USAGE:${NC}"
	echo '  webinterface-onboot [COMMANDS] [OPTIONS]'
	echo ''
	echo -e "${CYAN}COMMANDS:${NC}"
	echo '  apply-hack        Apply webinterface-onboot hack for versions >= v2.15'
	echo '  revert-hack       Revert webinterface-onboot hack'
	echo '  apply-prstip      Apply persist ip modification'
	echo '  revert-prstip     Revert persist ip modification'
	echo '  local-exec        Run webinterface-onboot in current shell'
	echo ''
	echo -e "${CYAN}OPTIONS:${NC}"
	echo '  -s, --status      Status of webinterface-onboot'
	echo '  -y, --no-prompt   Do not prompt for confirmation'
	echo '  -h, --help        Show help'
}

run_vars() {
	user_conf='/home/root/.config/remarkable/xochitl.conf'
	usb0iprange='10.11.99.1/32'
}

run() {
	run_vars
	echo -e "Setting WebInterfaceEnabled=true in ${user_conf}"
	sed -i 's/WebInterfaceEnabled=false/WebInterfaceEnabled=true/g' "$user_conf"
	echo -e "${GREEN}Set WebInterfaceEnabled=true in ${user_conf}${NC}"

	echo "Adding ${usb0iprange} ip address to usb0"
	ip addr change $usb0iprange dev usb0
	echo -e "${GREEN}Added ${usb0iprange} ip address to usb0${NC}"
}

get_version() {
	conf_file='/usr/share/remarkable/update.conf'
	if ! [ -f $conf_file ]; then
		echo "Error: Can't find ${conf_file}"
		exit 1
	fi
	xo_version=$(grep 'REMARKABLE_RELEASE_VERSION' $conf_file | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
	IFS=. read -r versA versB _ _ <<<"$xo_version"

	if [ "$versA" -eq 2 ] && [ "$versB" -ge 15 ] || [ "$versA" -ge 3 ]; then
		is_hack_version=true
	else
		is_hack_version=false
	fi
}

help_vars() {
	get_version
	xo='xochitl'
	xo_file="/usr/bin/${xo}"
	share_rel='share/webinterface-onboot'
	storage_rel="${share_rel}/xochitl_backups"
	storage_dir="/home/root/.local/${storage_rel}"
	bak_xo="${storage_dir}/${xo}-${xo_version}-bak"
	tmp_xo="${storage_dir}/.${xo}.tmp"
}

status() {
	run_vars
	help_vars

	echo -e "${CYAN}[${NC}XOCHITL WEB INTERFACE${CYAN}]"
	if netstat -tuln | grep -qE "10.11.99.1:80.*LISTEN"; then
		echo -e "${GREEN}Running${NC}"
	else
		echo -e "${RED}Not running${NC}"
	fi
	echo ''
	echo -e "${CYAN}[${NC}usb0 NETWORK INTERFACE${CYAN}]"
	if ip a | grep -qE "10.11.99.1/[32|29]"; then
		echo -e "${GREEN}Has 10.11.99.1 ip address${NC}"
	else
		echo -e "${YELLOW}Does not have 10.11.99.1 ip address${NC}"
	fi
	echo ''
	echo -e "${CYAN}[${NC}usb0 CABLE${CYAN}]"
	if [ "$(cat /sys/class/net/usb0/operstate)" == "up" ]; then
		echo -e "${PURPLE}connected${NC}"
	else
		echo -e "${CYAN}not connected${NC}"
	fi

	# # ------------------------ SERVICE ------------------------
	# main_service='webinterface-onboot.service'
	# echo ''
	# echo -e "${CYAN}[${NC}SERVICE${CYAN}]"
	# echo -e "${PURPLE}webinterface-onboot:${NC}"
	# if systemctl --quiet is-enabled "$main_service" 2>/dev/null; then
	# 	echo -n " - enabled"
	# else
	# 	echo -n " - disabled"
	# fi
	# if ! systemctl --quiet is-failed "$main_service" 2>/dev/null; then
	# 	echo ", no errors"
	# else
	# 	echo ", error when running"
	# fi
	# # ------------------------ SERVICE ------------------------

	vars_prstip
	echo ''
	echo -e "${CYAN}[${NC}PERSIST IP${CYAN}]"
	if is_action_moded "$prstip_content"; then
		echo -e "${GREEN}Currently applied${NC}"
	else
		echo -e "${YELLOW}Not currently applied${NC}"
	fi

	if [ "$is_hack_version" = false ]; then
		exit
	fi

	echo ''
	echo -e "${CYAN}[${NC}HACK${CYAN}]"
	if hack_applied "$xo_file"; then
		echo -e "${GREEN}Currently applied${NC}"
	else
		echo -e "${RED}Not currently applied${NC}"
		echo " - Run 'webinterface-onboot apply-hack' for correct function"
	fi

	echo ''
	echo -e "${CYAN}[${NC}BACKUPS${CYAN}]"
	backup_found=false

	opt_baks="/opt/${storage_rel}"
	if [ -d "$opt_baks" ]; then
		bak_files=$(find "$opt_baks" -name '*-bak*')
		if [ -n "$bak_files" ]; then
			backup_found=true
			echo -e "${CYAN}${opt_baks}${NC}"
			bak_files_xargs=$(echo "$bak_files" | xargs)
			IFS=' ' read -r -a arrayaa <<<"$bak_files_xargs"
			for element in "${arrayaa[@]}"; do
				IFS='/' read -r -a arrayab <<<"$element"
				echo " - ${arrayab[-1]}"
			done
		fi
	fi

	local_baks="/home/root/.local/${storage_rel}"
	if [ -d "$local_baks" ]; then
		bak_files=$(find "$local_baks" -name '*-bak*')
		if [ -n "$bak_files" ]; then
			backup_found=true
			echo -e "${CYAN}${local_baks}${NC}"
			bak_files_xargs=$(echo "$bak_files" | xargs)
			IFS=' ' read -r -a arrayab <<<"$bak_files_xargs"
			for element in "${arrayab[@]}"; do
				IFS='/' read -r -a arraybb <<<"$element"
				echo " - ${arraybb[-1]}"
			done
		fi
	fi

	if [ "$backup_found" = false ]; then
		echo -e "${RED}No backups found in:${NC}"
		echo -e "${opt_baks}"
		echo -e "${local_baks}"
	fi
}

hack_applied() {
	strings "$1" | grep usb | xargs | grep -q 'usbF usb0'
}

hack_possible() {
	strings "$1" | grep usb | xargs | grep -q 'usb0 usb1'
}

rm_temp() {
	echo "Removing ${tmp_xo}"
	[[ -f "$tmp_xo" ]] && rm $tmp_xo
}

apply_hack() {
	echo "webinterface-onboot hack for xochitl versions >= v2.15"
	echo ""
	help_vars
	if [ "$is_hack_version" = true ]; then
		echo "Compatible xochitl version: v${xo_version}"
	else
		echo "Incompatible xochitl version: v${xo_version}"
		exit 1
	fi
	echo "Applying the hack will:"
	echo " - Store a backup of '${xo_file}' at '${bak_xo}'."
	echo ""

	if hack_applied $xo_file; then
		echo "Hack already applied successfully"
		exit 0
	fi

	if hack_possible $xo_file; then
		echo "Hack can be applied"
	else
		echo "Error: Hack can't be applied, something is misconfigured"
		exit 1
	fi

	if [ "$no_prompt" = false ]; then
		read -r -p "Would you like to continue? [y/N] " response
		case "$response" in
		[yY][eE][sS] | [yY])
			echo "Applying webinterface-onboot hack"
			echo ""
			;;
		*)
			echo "Cancel webinterface-onboot hack"
			exit 0
			;;
		esac
	fi

	mkdir -p $storage_dir

	if cp "$xo_file" "$bak_xo"; then
		echo "Created ${bak_xo} file"
	else
		echo "Error: Create ${bak_xo} file"
		[[ -f "$bak_xo" ]] && rm "$bak_xo"
		exit 1
	fi

	if cp "$xo_file" "$tmp_xo"; then
		echo "Created ${tmp_xo} file"
	else
		echo "Error: Create ${tmp_xo} file"
		rm_temp
		exit 1
	fi

	# The entire hack. In the binary, change strings:
	#   'usb0' -> 'usbF'
	#   'usb1' -> 'usb0'
	if sed -i 's/usb0/usbF/g' "$tmp_xo" &&
		sed -i 's/usb1/usb0/g' "$tmp_xo"; then
		echo "Binary strings substituted"
	else
		echo "Error: Binary strings not substituted"
		rm_temp
		exit 1
	fi

	if hack_applied "$tmp_xo"; then
		echo "Temp hack application success"
	else
		echo "Error: Temp hack application failed"
		rm_temp
		exit 1
	fi

	if mv "$tmp_xo" "$xo_file"; then
		rm_temp
		echo ""
		echo "Success: webinterface-onboot hack applied"
		echo "Now run: systemctl restart xochitl"
		exit 0
	else
		echo "Error: mv ${tmp_xo} -> ${xo_file}"
		rm_temp

		if cp "$bak_xo" "$xo_file"; then
			echo "Recovery Success: ${xo_file} restored from ${bak_xo}"
		else
			echo "Recovery Error: cp ${bak_xo} -> ${xo_file}"
			exit 1
		fi
	fi
}

revert_hack() {
	echo "Revert webinterface-onboot hack"
	echo ""
	help_vars
	if [ "$is_hack_version" = true ]; then
		echo "Compatible xochitl version: v${xo_version}"
	else
		echo "Incompatible xochitl version: v${xo_version}"
		exit 1
	fi
	echo -e "This can be done if the backup file generated via the hack is found, "
	echo "or by applying the hack in reverse order."
	echo ""

	if hack_possible "$xo_file"; then
		echo "Initial hack has not been applied to this file, nothing to revert"
		exit 0
	fi
	if [ "$no_prompt" = false ]; then
		if [ -f "$bak_xo" ]; then
			echo "Backup file found: ${bak_xo}"
			read -r -p "Would you like to revert from backup file? [y/N] " response
			case "$response" in
			[yY][eE][sS] | [yY])
				echo "Reverting from backup file"
				if revert_from_backup; then
					exit 0
				fi
				;;
			*)
				echo "Cancel revert from backup file"
				;;
			esac
		else
			echo "Can't find backup file ${bak_xo}"
			echo "Backup files can be at ${STORAGE_HOME} or ${STORAGE_OPT}"
		fi
	fi

	if [ "$no_prompt" = false ]; then
		read -r -p "Would you like to revert by reversing hack? [y/N] " response
		case "$response" in
		[yY][eE][sS] | [yY])
			true
			;;
		*)
			echo "Cancel revert from reverse hack"
			exit 0
			;;
		esac
	fi
	hack_backwards
}

revert_from_backup() {
	echo ""
	if cp "$bak_xo" "$xo_file"; then
		echo "Success: Revert from backup file"
		echo "Now run: systemctl restart xochitl"
		return 0
	else
		echo "Error: Revert from backup file"
		return 1
	fi
}

hack_backwards() {
	echo ""
	if ! hack_applied "$xo_file"; then
		echo "File can not be reverted"
		exit 1
	else
		echo "File can be reverted"
	fi

	mkdir -p "$storage_dir"

	BAK_APPLIED="${bak_xo}-hack-applied"
	if cp "$xo_file" "$BAK_APPLIED"; then
		echo "Created ${BAK_APPLIED} file"
	else
		echo "Error: Create ${BAK_APPLIED} files"
		[[ -f $BAK_APPLIED ]] && rm "$BAK_APPLIED"
		exit 1
	fi

	if cp "$xo_file" "$tmp_xo"; then
		echo "Created ${tmp_xo} files"
	else
		echo "Error: Create ${tmp_xo} files"
		rm_temp
		exit 1
	fi

	if sed -i 's/usb0/usb1/g' "$tmp_xo" &&
		sed -i 's/usbF/usb0/g' "$tmp_xo"; then
		echo "Binary strings substituted"
	else
		echo "Error: Binary strings not substituted"
		rm_temp
		exit 1
	fi

	if hack_possible "$tmp_xo"; then
		echo "Temp hack reversion success"
	else
		echo "Error: Temp hack reversion failed"
		rm_temp
		exit 1
	fi

	if mv "$tmp_xo" "$xo_file"; then
		rm_temp
		echo ""
		echo "Success: webinterface-onboot hack reverted"
		echo "Now run: systemctl restart xochitl"
		exit 0
	else
		echo "Error: mv ${tmp_xo} -> ${xo_file}"
		rm_temp

		if cp "$BAK_APPLIED" "$xo_file"; then
			echo "Recovery Success: ${xo_file} restored from ${BAK_APPLIED}"
		else
			echo "Recovery Error: cp ${BAK_APPLIED} -> ${xo_file}"
			exit 1
		fi
	fi
}

vars_prstip() {
	get_version

	prstip_bak_dir='/home/root/.local/share/webinterface-onboot/prstip_backups'
	prstip_bak_file="$prstip_bak_dir/ifplugd.action-$xo_version-bak"

	prstip_file='/etc/ifplugd/ifplugd.action'
	prstip_content=$(cat $prstip_file)
	total_line=$(echo "$prstip_content" | wc -l)

	prstip_tmp="$prstip_bak_dir/.webint-onboot_prstip.ifplugd.action.tmp"
	ip_cmd="ip addr change 10.11.99.1/32 dev usb0"
}

is_action_moded() {
	echo "$1" | grep -qhE "$ip_cmd"
}

apply_prstip() {
	set -e
	vars_prstip

	echo "Applying webint-upldbtn will edit: $prstip_file"
	echo 'And create a backup at:'
	echo "$prstip_bak_file"
	echo ""

	if [ "$no_prompt" = false ]; then
		read -r -p "Would you like to continue? [y/N] " response
		case "$response" in
		[yY][eE][sS] | [yY])
			true
			;;
		*)
			echo "Cancel"
			exit
			;;
		esac
	fi
	apply_prstip_act
}

apply_prstip_act() {
	if is_action_moded "$prstip_content"; then
		echo "Persist ip already applied"
		exit
	fi

	mkdir -p "$prstip_bak_dir"
	cp "$prstip_file" "$prstip_bak_file"

	[[ -f $prstip_tmp ]] && rm "$prstip_tmp"
	cp "$prstip_file" "$prstip_tmp"

	stop_line=$(echo "$prstip_content" | grep -n 'systemctl stop' | cut -d : -f 1)
	root_line="$((stop_line + 1))"
	{
		echo "$prstip_content" | sed -n 1,"$stop_line"p
		echo "    $ip_cmd"
		echo "$prstip_content" | sed -n "$root_line","$total_line"p
	} >"$prstip_tmp"

	cp "$prstip_tmp" "$prstip_file" && rm "$prstip_tmp"
	echo "Persist ip applied"
}

revert_prstip() {
	set -e
	vars_prstip

	if [ "$no_prompt" = false ]; then
		read -r -p "Would you like to revert persist ip? [y/N] " response
		case "$response" in
		[yY][eE][sS] | [yY])
			true
			;;
		*)
			echo "Cancel"
			exit
			;;
		esac
	fi
	revert_prstip_act
}

revert_prstip_act() {
	if ! is_action_moded "$prstip_content"; then
		echo "Persist ip has not been applied"
		exit
	fi

	[[ -f "$prstip_tmp" ]] && rm "$prstip_tmp"
	cp "$prstip_file" "$prstip_tmp"

	stop_line=$(echo "$prstip_content" | grep -n "$ip_cmd" | cut -d : -f 1)
	stop_line="$((stop_line - 1))"
	root_line="$((stop_line + 2))"
	{
		sed -n 1,"$stop_line"p "$prstip_file"
		sed -n "$root_line","$total_line"p "$prstip_file"
	} >"$prstip_tmp"
	cp "$prstip_tmp" "$prstip_file" && rm "$prstip_tmp"
	echo "Persist ip reverted"
}

RED='\033[0;31m'
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

main "$@"
